{% set name = "svgpath2mpl" %}
{% set version = "1.0.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/svgpath2mpl-{{ version }}.tar.gz
  sha256: 73d0eb7cc106f05a1733cdc59ecd606423e04f9274923387d53b068e65a2f805

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - matplotlib-base
    - numpy
    - python >={{ python_min }}

test:
  imports:
    - svgpath2mpl
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/nvictus/svgpath2mpl
  summary: SVG path parser for matplotlib
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ickc
